theme: "hugo-PaperMod"
baseURL: https://cv-gustavo.netlify.app/
languageCode: en-us
title: CV José Gustavo Martins

params:
  ShowBreadCrumbs: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20 
